name: Testing the Python code

on:
  push:
    branches:
      - TEST

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f $GITHUB_WORKSPACE/rating/requirements.txt ]; then pip install -r $GITHUB_WORKSPACE/rating/requirements.txt; fi
      - name: Test with pytest
        run: |
          PYTHONPATH=./;./$GITHUB_WORKSPACE/rating/src/ pytest $GITHUB_WORKSPACE/rating/test
      - name: Install pycodestyle
        run: pip install pycodestyle
      - name: Lint with pycodestyle
        run: |
          pycodestyle $GITHUB_WORKSPACE/rating/src $GITHUB_WORKSPACE/rating/test

